//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.12 at 09:27:58 AM CET 
//

package no.bibsys.alma.rest.bibs;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;
import org.w3c.dom.Element;

/**
 * Bibliographic record object
 * 
 * <p>
 * Java class for bib complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="bib"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mms_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="record_format" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="linked_record_id" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="issn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="isbn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="complete_edition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="network_numbers" type="{}network_numbers" minOccurs="0"/&gt;
 *         &lt;element name="place_of_publication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="date_of_publication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="publisher_const" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="holdings" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="created_by" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="created_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="last_modified_by" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="last_modified_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="suppress_from_publishing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="originating_system" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="originating_system_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cataloging_level" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="warnings" type="{}warnings" minOccurs="0"/&gt;
 *         &lt;element name="requests" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;int"&gt;
 *                 &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bib", propOrder = {
        "mmsId",
        "recordFormat",
        "linkedRecordId",
        "title",
        "author",
        "issn",
        "isbn",
        "completeEdition",
        "networkNumbers",
        "placeOfPublication",
        "dateOfPublication",
        "publisherConst",
        "holdings",
        "createdBy",
        "createdDate",
        "lastModifiedBy",
        "lastModifiedDate",
        "suppressFromPublishing",
        "originatingSystem",
        "originatingSystemId",
        "catalogingLevel",
        "any",
        "warnings",
        "requests"
})
@XmlRootElement(name = "bib")
public class Bib implements Equals2, HashCode2, ToString2 {

    @XmlElement(name = "mms_id")
    protected String mmsId;
    @XmlElement(name = "record_format")
    protected String recordFormat;
    @XmlElement(name = "linked_record_id")
    protected LinkedRecordId linkedRecordId;
    protected String title;
    protected String author;
    protected String issn;
    protected String isbn;
    @XmlElement(name = "complete_edition")
    protected String completeEdition;
    @XmlElement(name = "network_numbers")
    protected NetworkNumbers networkNumbers;
    @XmlElement(name = "place_of_publication")
    protected String placeOfPublication;
    @XmlElement(name = "date_of_publication")
    protected String dateOfPublication;
    @XmlElement(name = "publisher_const")
    protected String publisherConst;
    protected Holdings holdings;
    @XmlElement(name = "created_by")
    protected String createdBy;
    @XmlElement(name = "created_date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar createdDate;
    @XmlElement(name = "last_modified_by")
    protected String lastModifiedBy;
    @XmlElement(name = "last_modified_date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastModifiedDate;
    @XmlElement(name = "suppress_from_publishing")
    protected String suppressFromPublishing;
    @XmlElement(name = "originating_system")
    protected String originatingSystem;
    @XmlElement(name = "originating_system_id")
    protected String originatingSystemId;
    @XmlElement(name = "cataloging_level")
    protected CatalogingLevel catalogingLevel;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    protected Warnings warnings;
    protected Requests requests;
    @XmlAttribute(name = "link")
    protected String link;

//    public Bib() {
//        super();
//    }
//    
//    public Bib(String mmsId) {
//        super();
//    }

    /**
     * Gets the value of the mmsId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMmsId() {
        return mmsId;
    }

    /**
     * Sets the value of the mmsId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMmsId(String value) {
        this.mmsId = value;
    }

    /**
     * Gets the value of the recordFormat property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRecordFormat() {
        return recordFormat;
    }

    /**
     * Sets the value of the recordFormat property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setRecordFormat(String value) {
        this.recordFormat = value;
    }

    /**
     * Gets the value of the linkedRecordId property.
     * 
     * @return possible object is {@link LinkedRecordId }
     * 
     */
    public LinkedRecordId getLinkedRecordId() {
        return linkedRecordId;
    }

    /**
     * Sets the value of the linkedRecordId property.
     * 
     * @param value allowed object is {@link LinkedRecordId }
     * 
     */
    public void setLinkedRecordId(LinkedRecordId value) {
        this.linkedRecordId = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the issn property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIssn() {
        return issn;
    }

    /**
     * Sets the value of the issn property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIssn(String value) {
        this.issn = value;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * Sets the value of the isbn property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIsbn(String value) {
        this.isbn = value;
    }

    /**
     * Gets the value of the completeEdition property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCompleteEdition() {
        return completeEdition;
    }

    /**
     * Sets the value of the completeEdition property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCompleteEdition(String value) {
        this.completeEdition = value;
    }

    /**
     * Gets the value of the networkNumbers property.
     * 
     * @return possible object is {@link NetworkNumbers }
     * 
     */
    public NetworkNumbers getNetworkNumbers() {
        return networkNumbers;
    }

    /**
     * Sets the value of the networkNumbers property.
     * 
     * @param value allowed object is {@link NetworkNumbers }
     * 
     */
    public void setNetworkNumbers(NetworkNumbers value) {
        this.networkNumbers = value;
    }

    /**
     * Gets the value of the placeOfPublication property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPlaceOfPublication() {
        return placeOfPublication;
    }

    /**
     * Sets the value of the placeOfPublication property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPlaceOfPublication(String value) {
        this.placeOfPublication = value;
    }

    /**
     * Gets the value of the dateOfPublication property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDateOfPublication() {
        return dateOfPublication;
    }

    /**
     * Sets the value of the dateOfPublication property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDateOfPublication(String value) {
        this.dateOfPublication = value;
    }

    /**
     * Gets the value of the publisherConst property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPublisherConst() {
        return publisherConst;
    }

    /**
     * Sets the value of the publisherConst property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPublisherConst(String value) {
        this.publisherConst = value;
    }

    /**
     * Gets the value of the holdings property.
     * 
     * @return possible object is {@link Holdings }
     * 
     */
    public Holdings getHoldings() {
        return holdings;
    }

    /**
     * Sets the value of the holdings property.
     * 
     * @param value allowed object is {@link Holdings }
     * 
     */
    public void setHoldings(Holdings value) {
        this.holdings = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCreatedBy(String value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the lastModifiedBy property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * Sets the value of the lastModifiedBy property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLastModifiedBy(String value) {
        this.lastModifiedBy = value;
    }

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setLastModifiedDate(XMLGregorianCalendar value) {
        this.lastModifiedDate = value;
    }

    /**
     * Gets the value of the suppressFromPublishing property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSuppressFromPublishing() {
        return suppressFromPublishing;
    }

    /**
     * Sets the value of the suppressFromPublishing property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSuppressFromPublishing(String value) {
        this.suppressFromPublishing = value;
    }

    /**
     * Gets the value of the originatingSystem property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOriginatingSystem() {
        return originatingSystem;
    }

    /**
     * Sets the value of the originatingSystem property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setOriginatingSystem(String value) {
        this.originatingSystem = value;
    }

    /**
     * Gets the value of the originatingSystemId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOriginatingSystemId() {
        return originatingSystemId;
    }

    /**
     * Sets the value of the originatingSystemId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setOriginatingSystemId(String value) {
        this.originatingSystemId = value;
    }

    /**
     * Gets the value of the catalogingLevel property.
     * 
     * @return possible object is {@link CatalogingLevel }
     * 
     */
    public CatalogingLevel getCatalogingLevel() {
        return catalogingLevel;
    }

    /**
     * Sets the value of the catalogingLevel property.
     * 
     * @param value allowed object is {@link CatalogingLevel }
     * 
     */
    public void setCatalogingLevel(CatalogingLevel value) {
        this.catalogingLevel = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the warnings property.
     * 
     * @return possible object is {@link Warnings }
     * 
     */
    public Warnings getWarnings() {
        return warnings;
    }

    /**
     * Sets the value of the warnings property.
     * 
     * @param value allowed object is {@link Warnings }
     * 
     */
    public void setWarnings(Warnings value) {
        this.warnings = value;
    }

    /**
     * Gets the value of the requests property.
     * 
     * @return possible object is {@link Requests }
     * 
     */
    public Requests getRequests() {
        return requests;
    }

    /**
     * Sets the value of the requests property.
     * 
     * @param value allowed object is {@link Requests }
     * 
     */
    public void setRequests(Requests value) {
        this.requests = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLink(String value) {
        this.link = value;
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            String theMmsId;
            theMmsId = this.getMmsId();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "mmsId", theMmsId), currentHashCode, theMmsId,
                            (this.mmsId != null));
        }
        {
            String theRecordFormat;
            theRecordFormat = this.getRecordFormat();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "recordFormat", theRecordFormat), currentHashCode,
                            theRecordFormat, (this.recordFormat != null));
        }
        {
            LinkedRecordId theLinkedRecordId;
            theLinkedRecordId = this.getLinkedRecordId();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "linkedRecordId", theLinkedRecordId),
                            currentHashCode, theLinkedRecordId, (this.linkedRecordId != null));
        }
        {
            String theTitle;
            theTitle = this.getTitle();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "title", theTitle), currentHashCode, theTitle,
                            (this.title != null));
        }
        {
            String theAuthor;
            theAuthor = this.getAuthor();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "author", theAuthor), currentHashCode, theAuthor,
                            (this.author != null));
        }
        {
            String theIssn;
            theIssn = this.getIssn();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "issn", theIssn), currentHashCode, theIssn,
                            (this.issn != null));
        }
        {
            String theIsbn;
            theIsbn = this.getIsbn();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "isbn", theIsbn), currentHashCode, theIsbn,
                            (this.isbn != null));
        }
        {
            String theCompleteEdition;
            theCompleteEdition = this.getCompleteEdition();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "completeEdition", theCompleteEdition),
                            currentHashCode, theCompleteEdition, (this.completeEdition != null));
        }
        {
            NetworkNumbers theNetworkNumbers;
            theNetworkNumbers = this.getNetworkNumbers();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "networkNumbers", theNetworkNumbers),
                            currentHashCode, theNetworkNumbers, (this.networkNumbers != null));
        }
        {
            String thePlaceOfPublication;
            thePlaceOfPublication = this.getPlaceOfPublication();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "placeOfPublication", thePlaceOfPublication),
                            currentHashCode, thePlaceOfPublication, (this.placeOfPublication != null));
        }
        {
            String theDateOfPublication;
            theDateOfPublication = this.getDateOfPublication();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "dateOfPublication", theDateOfPublication),
                            currentHashCode, theDateOfPublication, (this.dateOfPublication != null));
        }
        {
            String thePublisherConst;
            thePublisherConst = this.getPublisherConst();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "publisherConst", thePublisherConst),
                            currentHashCode, thePublisherConst, (this.publisherConst != null));
        }
        {
            Holdings theHoldings;
            theHoldings = this.getHoldings();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "holdings", theHoldings), currentHashCode,
                            theHoldings, (this.holdings != null));
        }
        {
            String theCreatedBy;
            theCreatedBy = this.getCreatedBy();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "createdBy", theCreatedBy), currentHashCode,
                            theCreatedBy, (this.createdBy != null));
        }
        {
            XMLGregorianCalendar theCreatedDate;
            theCreatedDate = this.getCreatedDate();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "createdDate", theCreatedDate), currentHashCode,
                            theCreatedDate, (this.createdDate != null));
        }
        {
            String theLastModifiedBy;
            theLastModifiedBy = this.getLastModifiedBy();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "lastModifiedBy", theLastModifiedBy),
                            currentHashCode, theLastModifiedBy, (this.lastModifiedBy != null));
        }
        {
            XMLGregorianCalendar theLastModifiedDate;
            theLastModifiedDate = this.getLastModifiedDate();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "lastModifiedDate", theLastModifiedDate),
                            currentHashCode, theLastModifiedDate, (this.lastModifiedDate != null));
        }
        {
            String theSuppressFromPublishing;
            theSuppressFromPublishing = this.getSuppressFromPublishing();
            currentHashCode =
                    strategy.hashCode(
                            LocatorUtils.property(locator, "suppressFromPublishing", theSuppressFromPublishing),
                            currentHashCode, theSuppressFromPublishing, (this.suppressFromPublishing != null));
        }
        {
            String theOriginatingSystem;
            theOriginatingSystem = this.getOriginatingSystem();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "originatingSystem", theOriginatingSystem),
                            currentHashCode, theOriginatingSystem, (this.originatingSystem != null));
        }
        {
            String theOriginatingSystemId;
            theOriginatingSystemId = this.getOriginatingSystemId();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "originatingSystemId", theOriginatingSystemId),
                            currentHashCode, theOriginatingSystemId, (this.originatingSystemId != null));
        }
        {
            CatalogingLevel theCatalogingLevel;
            theCatalogingLevel = this.getCatalogingLevel();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "catalogingLevel", theCatalogingLevel),
                            currentHashCode, theCatalogingLevel, (this.catalogingLevel != null));
        }
        {
            List<Object> theAny;
            theAny = (((this.any != null) && (!this.any.isEmpty())) ? this.getAny() : null);
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "any", theAny), currentHashCode, theAny,
                            ((this.any != null) && (!this.any.isEmpty())));
        }
        {
            Warnings theWarnings;
            theWarnings = this.getWarnings();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "warnings", theWarnings), currentHashCode,
                            theWarnings, (this.warnings != null));
        }
        {
            Requests theRequests;
            theRequests = this.getRequests();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "requests", theRequests), currentHashCode,
                            theRequests, (this.requests != null));
        }
        {
            String theLink;
            theLink = this.getLink();
            currentHashCode =
                    strategy.hashCode(LocatorUtils.property(locator, "link", theLink), currentHashCode, theLink,
                            (this.link != null));
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object,
            EqualsStrategy2 strategy) {
        if ((object == null) || (this.getClass() != object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Bib that = ((Bib) object);
        {
            String lhsMmsId;
            lhsMmsId = this.getMmsId();
            String rhsMmsId;
            rhsMmsId = that.getMmsId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "mmsId", lhsMmsId),
                    LocatorUtils.property(thatLocator, "mmsId", rhsMmsId), lhsMmsId, rhsMmsId, (this.mmsId != null),
                    (that.mmsId != null))) {
                return false;
            }
        }
        {
            String lhsRecordFormat;
            lhsRecordFormat = this.getRecordFormat();
            String rhsRecordFormat;
            rhsRecordFormat = that.getRecordFormat();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "recordFormat", lhsRecordFormat),
                    LocatorUtils.property(thatLocator, "recordFormat", rhsRecordFormat), lhsRecordFormat,
                    rhsRecordFormat, (this.recordFormat != null), (that.recordFormat != null))) {
                return false;
            }
        }
        {
            LinkedRecordId lhsLinkedRecordId;
            lhsLinkedRecordId = this.getLinkedRecordId();
            LinkedRecordId rhsLinkedRecordId;
            rhsLinkedRecordId = that.getLinkedRecordId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "linkedRecordId", lhsLinkedRecordId),
                    LocatorUtils.property(thatLocator, "linkedRecordId", rhsLinkedRecordId), lhsLinkedRecordId,
                    rhsLinkedRecordId, (this.linkedRecordId != null), (that.linkedRecordId != null))) {
                return false;
            }
        }
        {
            String lhsTitle;
            lhsTitle = this.getTitle();
            String rhsTitle;
            rhsTitle = that.getTitle();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "title", lhsTitle),
                    LocatorUtils.property(thatLocator, "title", rhsTitle), lhsTitle, rhsTitle, (this.title != null),
                    (that.title != null))) {
                return false;
            }
        }
        {
            String lhsAuthor;
            lhsAuthor = this.getAuthor();
            String rhsAuthor;
            rhsAuthor = that.getAuthor();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "author", lhsAuthor),
                    LocatorUtils.property(thatLocator, "author", rhsAuthor), lhsAuthor, rhsAuthor,
                    (this.author != null), (that.author != null))) {
                return false;
            }
        }
        {
            String lhsIssn;
            lhsIssn = this.getIssn();
            String rhsIssn;
            rhsIssn = that.getIssn();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "issn", lhsIssn),
                    LocatorUtils.property(thatLocator, "issn", rhsIssn), lhsIssn, rhsIssn, (this.issn != null),
                    (that.issn != null))) {
                return false;
            }
        }
        {
            String lhsIsbn;
            lhsIsbn = this.getIsbn();
            String rhsIsbn;
            rhsIsbn = that.getIsbn();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "isbn", lhsIsbn),
                    LocatorUtils.property(thatLocator, "isbn", rhsIsbn), lhsIsbn, rhsIsbn, (this.isbn != null),
                    (that.isbn != null))) {
                return false;
            }
        }
        {
            String lhsCompleteEdition;
            lhsCompleteEdition = this.getCompleteEdition();
            String rhsCompleteEdition;
            rhsCompleteEdition = that.getCompleteEdition();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "completeEdition", lhsCompleteEdition),
                    LocatorUtils.property(thatLocator, "completeEdition", rhsCompleteEdition), lhsCompleteEdition,
                    rhsCompleteEdition, (this.completeEdition != null), (that.completeEdition != null))) {
                return false;
            }
        }
        {
            NetworkNumbers lhsNetworkNumbers;
            lhsNetworkNumbers = this.getNetworkNumbers();
            NetworkNumbers rhsNetworkNumbers;
            rhsNetworkNumbers = that.getNetworkNumbers();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "networkNumbers", lhsNetworkNumbers),
                    LocatorUtils.property(thatLocator, "networkNumbers", rhsNetworkNumbers), lhsNetworkNumbers,
                    rhsNetworkNumbers, (this.networkNumbers != null), (that.networkNumbers != null))) {
                return false;
            }
        }
        {
            String lhsPlaceOfPublication;
            lhsPlaceOfPublication = this.getPlaceOfPublication();
            String rhsPlaceOfPublication;
            rhsPlaceOfPublication = that.getPlaceOfPublication();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "placeOfPublication", lhsPlaceOfPublication),
                    LocatorUtils.property(thatLocator, "placeOfPublication", rhsPlaceOfPublication),
                    lhsPlaceOfPublication, rhsPlaceOfPublication, (this.placeOfPublication != null),
                    (that.placeOfPublication != null))) {
                return false;
            }
        }
        {
            String lhsDateOfPublication;
            lhsDateOfPublication = this.getDateOfPublication();
            String rhsDateOfPublication;
            rhsDateOfPublication = that.getDateOfPublication();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "dateOfPublication", lhsDateOfPublication),
                    LocatorUtils.property(thatLocator, "dateOfPublication", rhsDateOfPublication), lhsDateOfPublication,
                    rhsDateOfPublication, (this.dateOfPublication != null), (that.dateOfPublication != null))) {
                return false;
            }
        }
        {
            String lhsPublisherConst;
            lhsPublisherConst = this.getPublisherConst();
            String rhsPublisherConst;
            rhsPublisherConst = that.getPublisherConst();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "publisherConst", lhsPublisherConst),
                    LocatorUtils.property(thatLocator, "publisherConst", rhsPublisherConst), lhsPublisherConst,
                    rhsPublisherConst, (this.publisherConst != null), (that.publisherConst != null))) {
                return false;
            }
        }
        {
            Holdings lhsHoldings;
            lhsHoldings = this.getHoldings();
            Holdings rhsHoldings;
            rhsHoldings = that.getHoldings();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "holdings", lhsHoldings),
                    LocatorUtils.property(thatLocator, "holdings", rhsHoldings), lhsHoldings, rhsHoldings,
                    (this.holdings != null), (that.holdings != null))) {
                return false;
            }
        }
        {
            String lhsCreatedBy;
            lhsCreatedBy = this.getCreatedBy();
            String rhsCreatedBy;
            rhsCreatedBy = that.getCreatedBy();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "createdBy", lhsCreatedBy),
                    LocatorUtils.property(thatLocator, "createdBy", rhsCreatedBy), lhsCreatedBy, rhsCreatedBy,
                    (this.createdBy != null), (that.createdBy != null))) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsCreatedDate;
            lhsCreatedDate = this.getCreatedDate();
            XMLGregorianCalendar rhsCreatedDate;
            rhsCreatedDate = that.getCreatedDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "createdDate", lhsCreatedDate),
                    LocatorUtils.property(thatLocator, "createdDate", rhsCreatedDate), lhsCreatedDate, rhsCreatedDate,
                    (this.createdDate != null), (that.createdDate != null))) {
                return false;
            }
        }
        {
            String lhsLastModifiedBy;
            lhsLastModifiedBy = this.getLastModifiedBy();
            String rhsLastModifiedBy;
            rhsLastModifiedBy = that.getLastModifiedBy();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "lastModifiedBy", lhsLastModifiedBy),
                    LocatorUtils.property(thatLocator, "lastModifiedBy", rhsLastModifiedBy), lhsLastModifiedBy,
                    rhsLastModifiedBy, (this.lastModifiedBy != null), (that.lastModifiedBy != null))) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsLastModifiedDate;
            lhsLastModifiedDate = this.getLastModifiedDate();
            XMLGregorianCalendar rhsLastModifiedDate;
            rhsLastModifiedDate = that.getLastModifiedDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "lastModifiedDate", lhsLastModifiedDate),
                    LocatorUtils.property(thatLocator, "lastModifiedDate", rhsLastModifiedDate), lhsLastModifiedDate,
                    rhsLastModifiedDate, (this.lastModifiedDate != null), (that.lastModifiedDate != null))) {
                return false;
            }
        }
        {
            String lhsSuppressFromPublishing;
            lhsSuppressFromPublishing = this.getSuppressFromPublishing();
            String rhsSuppressFromPublishing;
            rhsSuppressFromPublishing = that.getSuppressFromPublishing();
            if (!strategy.equals(
                    LocatorUtils.property(thisLocator, "suppressFromPublishing", lhsSuppressFromPublishing),
                    LocatorUtils.property(thatLocator, "suppressFromPublishing", rhsSuppressFromPublishing),
                    lhsSuppressFromPublishing, rhsSuppressFromPublishing, (this.suppressFromPublishing != null),
                    (that.suppressFromPublishing != null))) {
                return false;
            }
        }
        {
            String lhsOriginatingSystem;
            lhsOriginatingSystem = this.getOriginatingSystem();
            String rhsOriginatingSystem;
            rhsOriginatingSystem = that.getOriginatingSystem();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "originatingSystem", lhsOriginatingSystem),
                    LocatorUtils.property(thatLocator, "originatingSystem", rhsOriginatingSystem), lhsOriginatingSystem,
                    rhsOriginatingSystem, (this.originatingSystem != null), (that.originatingSystem != null))) {
                return false;
            }
        }
        {
            String lhsOriginatingSystemId;
            lhsOriginatingSystemId = this.getOriginatingSystemId();
            String rhsOriginatingSystemId;
            rhsOriginatingSystemId = that.getOriginatingSystemId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "originatingSystemId", lhsOriginatingSystemId),
                    LocatorUtils.property(thatLocator, "originatingSystemId", rhsOriginatingSystemId),
                    lhsOriginatingSystemId, rhsOriginatingSystemId, (this.originatingSystemId != null),
                    (that.originatingSystemId != null))) {
                return false;
            }
        }
        {
            CatalogingLevel lhsCatalogingLevel;
            lhsCatalogingLevel = this.getCatalogingLevel();
            CatalogingLevel rhsCatalogingLevel;
            rhsCatalogingLevel = that.getCatalogingLevel();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "catalogingLevel", lhsCatalogingLevel),
                    LocatorUtils.property(thatLocator, "catalogingLevel", rhsCatalogingLevel), lhsCatalogingLevel,
                    rhsCatalogingLevel, (this.catalogingLevel != null), (that.catalogingLevel != null))) {
                return false;
            }
        }
        {
            List<Object> lhsAny;
            lhsAny = (((this.any != null) && (!this.any.isEmpty())) ? this.getAny() : null);
            List<Object> rhsAny;
            rhsAny = (((that.any != null) && (!that.any.isEmpty())) ? that.getAny() : null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "any", lhsAny),
                    LocatorUtils.property(thatLocator, "any", rhsAny), lhsAny, rhsAny,
                    ((this.any != null) && (!this.any.isEmpty())), ((that.any != null) && (!that.any.isEmpty())))) {
                return false;
            }
        }
        {
            Warnings lhsWarnings;
            lhsWarnings = this.getWarnings();
            Warnings rhsWarnings;
            rhsWarnings = that.getWarnings();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "warnings", lhsWarnings),
                    LocatorUtils.property(thatLocator, "warnings", rhsWarnings), lhsWarnings, rhsWarnings,
                    (this.warnings != null), (that.warnings != null))) {
                return false;
            }
        }
        {
            Requests lhsRequests;
            lhsRequests = this.getRequests();
            Requests rhsRequests;
            rhsRequests = that.getRequests();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "requests", lhsRequests),
                    LocatorUtils.property(thatLocator, "requests", rhsRequests), lhsRequests, rhsRequests,
                    (this.requests != null), (that.requests != null))) {
                return false;
            }
        }
        {
            String lhsLink;
            lhsLink = this.getLink();
            String rhsLink;
            rhsLink = that.getLink();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "link", lhsLink),
                    LocatorUtils.property(thatLocator, "link", rhsLink), lhsLink, rhsLink, (this.link != null),
                    (that.link != null))) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            String theMmsId;
            theMmsId = this.getMmsId();
            strategy.appendField(locator, this, "mmsId", buffer, theMmsId, (this.mmsId != null));
        }
        {
            String theRecordFormat;
            theRecordFormat = this.getRecordFormat();
            strategy.appendField(locator, this, "recordFormat", buffer, theRecordFormat, (this.recordFormat != null));
        }
        {
            LinkedRecordId theLinkedRecordId;
            theLinkedRecordId = this.getLinkedRecordId();
            strategy.appendField(locator, this, "linkedRecordId", buffer, theLinkedRecordId,
                    (this.linkedRecordId != null));
        }
        {
            String theTitle;
            theTitle = this.getTitle();
            strategy.appendField(locator, this, "title", buffer, theTitle, (this.title != null));
        }
        {
            String theAuthor;
            theAuthor = this.getAuthor();
            strategy.appendField(locator, this, "author", buffer, theAuthor, (this.author != null));
        }
        {
            String theIssn;
            theIssn = this.getIssn();
            strategy.appendField(locator, this, "issn", buffer, theIssn, (this.issn != null));
        }
        {
            String theIsbn;
            theIsbn = this.getIsbn();
            strategy.appendField(locator, this, "isbn", buffer, theIsbn, (this.isbn != null));
        }
        {
            String theCompleteEdition;
            theCompleteEdition = this.getCompleteEdition();
            strategy.appendField(locator, this, "completeEdition", buffer, theCompleteEdition,
                    (this.completeEdition != null));
        }
        {
            NetworkNumbers theNetworkNumbers;
            theNetworkNumbers = this.getNetworkNumbers();
            strategy.appendField(locator, this, "networkNumbers", buffer, theNetworkNumbers,
                    (this.networkNumbers != null));
        }
        {
            String thePlaceOfPublication;
            thePlaceOfPublication = this.getPlaceOfPublication();
            strategy.appendField(locator, this, "placeOfPublication", buffer, thePlaceOfPublication,
                    (this.placeOfPublication != null));
        }
        {
            String theDateOfPublication;
            theDateOfPublication = this.getDateOfPublication();
            strategy.appendField(locator, this, "dateOfPublication", buffer, theDateOfPublication,
                    (this.dateOfPublication != null));
        }
        {
            String thePublisherConst;
            thePublisherConst = this.getPublisherConst();
            strategy.appendField(locator, this, "publisherConst", buffer, thePublisherConst,
                    (this.publisherConst != null));
        }
        {
            Holdings theHoldings;
            theHoldings = this.getHoldings();
            strategy.appendField(locator, this, "holdings", buffer, theHoldings, (this.holdings != null));
        }
        {
            String theCreatedBy;
            theCreatedBy = this.getCreatedBy();
            strategy.appendField(locator, this, "createdBy", buffer, theCreatedBy, (this.createdBy != null));
        }
        {
            XMLGregorianCalendar theCreatedDate;
            theCreatedDate = this.getCreatedDate();
            strategy.appendField(locator, this, "createdDate", buffer, theCreatedDate, (this.createdDate != null));
        }
        {
            String theLastModifiedBy;
            theLastModifiedBy = this.getLastModifiedBy();
            strategy.appendField(locator, this, "lastModifiedBy", buffer, theLastModifiedBy,
                    (this.lastModifiedBy != null));
        }
        {
            XMLGregorianCalendar theLastModifiedDate;
            theLastModifiedDate = this.getLastModifiedDate();
            strategy.appendField(locator, this, "lastModifiedDate", buffer, theLastModifiedDate,
                    (this.lastModifiedDate != null));
        }
        {
            String theSuppressFromPublishing;
            theSuppressFromPublishing = this.getSuppressFromPublishing();
            strategy.appendField(locator, this, "suppressFromPublishing", buffer, theSuppressFromPublishing,
                    (this.suppressFromPublishing != null));
        }
        {
            String theOriginatingSystem;
            theOriginatingSystem = this.getOriginatingSystem();
            strategy.appendField(locator, this, "originatingSystem", buffer, theOriginatingSystem,
                    (this.originatingSystem != null));
        }
        {
            String theOriginatingSystemId;
            theOriginatingSystemId = this.getOriginatingSystemId();
            strategy.appendField(locator, this, "originatingSystemId", buffer, theOriginatingSystemId,
                    (this.originatingSystemId != null));
        }
        {
            CatalogingLevel theCatalogingLevel;
            theCatalogingLevel = this.getCatalogingLevel();
            strategy.appendField(locator, this, "catalogingLevel", buffer, theCatalogingLevel,
                    (this.catalogingLevel != null));
        }
        {
            List<Object> theAny;
            theAny = (((this.any != null) && (!this.any.isEmpty())) ? this.getAny() : null);
            strategy.appendField(locator, this, "any", buffer, theAny, ((this.any != null) && (!this.any.isEmpty())));
        }
        {
            Warnings theWarnings;
            theWarnings = this.getWarnings();
            strategy.appendField(locator, this, "warnings", buffer, theWarnings, (this.warnings != null));
        }
        {
            Requests theRequests;
            theRequests = this.getRequests();
            strategy.appendField(locator, this, "requests", buffer, theRequests, (this.requests != null));
        }
        {
            String theLink;
            theLink = this.getLink();
            strategy.appendField(locator, this, "link", buffer, theLink, (this.link != null));
        }
        return buffer;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within
     * this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class CatalogingLevel implements Equals2, HashCode2, ToString2 {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setDesc(String value) {
            this.desc = value;
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
            int currentHashCode = 1;
            {
                String theValue;
                theValue = this.getValue();
                currentHashCode =
                        strategy.hashCode(LocatorUtils.property(locator, "value", theValue), currentHashCode, theValue,
                                (this.value != null));
            }
            {
                String theDesc;
                theDesc = this.getDesc();
                currentHashCode =
                        strategy.hashCode(LocatorUtils.property(locator, "desc", theDesc), currentHashCode, theDesc,
                                (this.desc != null));
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object,
                EqualsStrategy2 strategy) {
            if ((object == null) || (this.getClass() != object.getClass())) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final CatalogingLevel that = ((CatalogingLevel) object);
            {
                String lhsValue;
                lhsValue = this.getValue();
                String rhsValue;
                rhsValue = that.getValue();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "value", lhsValue),
                        LocatorUtils.property(thatLocator, "value", rhsValue), lhsValue, rhsValue, (this.value != null),
                        (that.value != null))) {
                    return false;
                }
            }
            {
                String lhsDesc;
                lhsDesc = this.getDesc();
                String rhsDesc;
                rhsDesc = that.getDesc();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "desc", lhsDesc),
                        LocatorUtils.property(thatLocator, "desc", rhsDesc), lhsDesc, rhsDesc, (this.desc != null),
                        (that.desc != null))) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                String theValue;
                theValue = this.getValue();
                strategy.appendField(locator, this, "value", buffer, theValue, (this.value != null));
            }
            {
                String theDesc;
                theDesc = this.getDesc();
                strategy.appendField(locator, this, "desc", buffer, theDesc, (this.desc != null));
            }
            return buffer;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within
     * this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class Holdings implements Equals2, HashCode2, ToString2 {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "link")
        protected String link;

        /**
         * Gets the value of the value property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the link property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setLink(String value) {
            this.link = value;
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
            int currentHashCode = 1;
            {
                String theValue;
                theValue = this.getValue();
                currentHashCode =
                        strategy.hashCode(LocatorUtils.property(locator, "value", theValue), currentHashCode, theValue,
                                (this.value != null));
            }
            {
                String theLink;
                theLink = this.getLink();
                currentHashCode =
                        strategy.hashCode(LocatorUtils.property(locator, "link", theLink), currentHashCode, theLink,
                                (this.link != null));
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object,
                EqualsStrategy2 strategy) {
            if ((object == null) || (this.getClass() != object.getClass())) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final Holdings that = ((Holdings) object);
            {
                String lhsValue;
                lhsValue = this.getValue();
                String rhsValue;
                rhsValue = that.getValue();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "value", lhsValue),
                        LocatorUtils.property(thatLocator, "value", rhsValue), lhsValue, rhsValue, (this.value != null),
                        (that.value != null))) {
                    return false;
                }
            }
            {
                String lhsLink;
                lhsLink = this.getLink();
                String rhsLink;
                rhsLink = that.getLink();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "link", lhsLink),
                        LocatorUtils.property(thatLocator, "link", rhsLink), lhsLink, rhsLink, (this.link != null),
                        (that.link != null))) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                String theValue;
                theValue = this.getValue();
                strategy.appendField(locator, this, "value", buffer, theValue, (this.value != null));
            }
            {
                String theLink;
                theLink = this.getLink();
                strategy.appendField(locator, this, "link", buffer, theLink, (this.link != null));
            }
            return buffer;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within
     * this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class LinkedRecordId implements Equals2, HashCode2, ToString2 {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "type")
        protected String type;

        /**
         * Gets the value of the value property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setType(String value) {
            this.type = value;
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
            int currentHashCode = 1;
            {
                String theValue;
                theValue = this.getValue();
                currentHashCode =
                        strategy.hashCode(LocatorUtils.property(locator, "value", theValue), currentHashCode, theValue,
                                (this.value != null));
            }
            {
                String theType;
                theType = this.getType();
                currentHashCode =
                        strategy.hashCode(LocatorUtils.property(locator, "type", theType), currentHashCode, theType,
                                (this.type != null));
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object,
                EqualsStrategy2 strategy) {
            if ((object == null) || (this.getClass() != object.getClass())) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final LinkedRecordId that = ((LinkedRecordId) object);
            {
                String lhsValue;
                lhsValue = this.getValue();
                String rhsValue;
                rhsValue = that.getValue();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "value", lhsValue),
                        LocatorUtils.property(thatLocator, "value", rhsValue), lhsValue, rhsValue, (this.value != null),
                        (that.value != null))) {
                    return false;
                }
            }
            {
                String lhsType;
                lhsType = this.getType();
                String rhsType;
                rhsType = that.getType();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "type", lhsType),
                        LocatorUtils.property(thatLocator, "type", rhsType), lhsType, rhsType, (this.type != null),
                        (that.type != null))) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                String theValue;
                theValue = this.getValue();
                strategy.appendField(locator, this, "value", buffer, theValue, (this.value != null));
            }
            {
                String theType;
                theType = this.getType();
                strategy.appendField(locator, this, "type", buffer, theType, (this.type != null));
            }
            return buffer;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within
     * this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;int"&gt;
     *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class Requests implements Equals2, HashCode2, ToString2 {

        @XmlValue
        protected int value;
        @XmlAttribute(name = "link")
        protected String link;

        /**
         * Gets the value of the value property.
         * 
         */
        public int getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(int value) {
            this.value = value;
        }

        /**
         * Gets the value of the link property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setLink(String value) {
            this.link = value;
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
            int currentHashCode = 1;
            {
                int theValue;
                theValue = this.getValue();
                currentHashCode =
                        strategy.hashCode(LocatorUtils.property(locator, "value", theValue), currentHashCode, theValue,
                                true);
            }
            {
                String theLink;
                theLink = this.getLink();
                currentHashCode =
                        strategy.hashCode(LocatorUtils.property(locator, "link", theLink), currentHashCode, theLink,
                                (this.link != null));
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object,
                EqualsStrategy2 strategy) {
            if ((object == null) || (this.getClass() != object.getClass())) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final Requests that = ((Requests) object);
            {
                int lhsValue;
                lhsValue = this.getValue();
                int rhsValue;
                rhsValue = that.getValue();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "value", lhsValue),
                        LocatorUtils.property(thatLocator, "value", rhsValue), lhsValue, rhsValue, true, true)) {
                    return false;
                }
            }
            {
                String lhsLink;
                lhsLink = this.getLink();
                String rhsLink;
                rhsLink = that.getLink();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "link", lhsLink),
                        LocatorUtils.property(thatLocator, "link", rhsLink), lhsLink, rhsLink, (this.link != null),
                        (that.link != null))) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                int theValue;
                theValue = this.getValue();
                strategy.appendField(locator, this, "value", buffer, theValue, true);
            }
            {
                String theLink;
                theLink = this.getLink();
                strategy.appendField(locator, this, "link", buffer, theLink, (this.link != null));
            }
            return buffer;
        }

    }

}
