//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.12 at 09:28:09 AM CET 
//


package no.bibsys.alma.rest.partner;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * FULFILLMENT_NETWORK related details. Relevant and mandatory only if profile_type = FULFILLMENT_NETWORK.
 * 
 * <p>Java class for fulfillment_network_details complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fulfillment_network_details"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="fulfillment_network_customer_code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fulfillment_network_url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="request_expiry_type" type="{}request_expiry_type"/&gt;
 *         &lt;element name="expiry_time" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fulfillment_network_details", propOrder = {

})
public class FulfillmentNetworkDetails implements Serializable, Equals2, HashCode2, ToString2
{

    @XmlElement(name = "fulfillment_network_customer_code", required = true)
    protected String fulfillmentNetworkCustomerCode;
    @XmlElement(name = "fulfillment_network_url", required = true)
    protected String fulfillmentNetworkUrl;
    @XmlElement(name = "request_expiry_type", required = true)
    protected RequestExpiryType requestExpiryType;
    @XmlElement(name = "expiry_time")
    protected Integer expiryTime;

    /**
     * Gets the value of the fulfillmentNetworkCustomerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulfillmentNetworkCustomerCode() {
        return fulfillmentNetworkCustomerCode;
    }

    /**
     * Sets the value of the fulfillmentNetworkCustomerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulfillmentNetworkCustomerCode(String value) {
        this.fulfillmentNetworkCustomerCode = value;
    }

    /**
     * Gets the value of the fulfillmentNetworkUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulfillmentNetworkUrl() {
        return fulfillmentNetworkUrl;
    }

    /**
     * Sets the value of the fulfillmentNetworkUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulfillmentNetworkUrl(String value) {
        this.fulfillmentNetworkUrl = value;
    }

    /**
     * Gets the value of the requestExpiryType property.
     * 
     * @return
     *     possible object is
     *     {@link RequestExpiryType }
     *     
     */
    public RequestExpiryType getRequestExpiryType() {
        return requestExpiryType;
    }

    /**
     * Sets the value of the requestExpiryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestExpiryType }
     *     
     */
    public void setRequestExpiryType(RequestExpiryType value) {
        this.requestExpiryType = value;
    }

    /**
     * Gets the value of the expiryTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExpiryTime() {
        return expiryTime;
    }

    /**
     * Sets the value of the expiryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExpiryTime(Integer value) {
        this.expiryTime = value;
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            String theFulfillmentNetworkCustomerCode;
            theFulfillmentNetworkCustomerCode = this.getFulfillmentNetworkCustomerCode();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fulfillmentNetworkCustomerCode", theFulfillmentNetworkCustomerCode), currentHashCode, theFulfillmentNetworkCustomerCode, (this.fulfillmentNetworkCustomerCode!= null));
        }
        {
            String theFulfillmentNetworkUrl;
            theFulfillmentNetworkUrl = this.getFulfillmentNetworkUrl();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fulfillmentNetworkUrl", theFulfillmentNetworkUrl), currentHashCode, theFulfillmentNetworkUrl, (this.fulfillmentNetworkUrl!= null));
        }
        {
            RequestExpiryType theRequestExpiryType;
            theRequestExpiryType = this.getRequestExpiryType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "requestExpiryType", theRequestExpiryType), currentHashCode, theRequestExpiryType, (this.requestExpiryType!= null));
        }
        {
            Integer theExpiryTime;
            theExpiryTime = this.getExpiryTime();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "expiryTime", theExpiryTime), currentHashCode, theExpiryTime, (this.expiryTime!= null));
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final FulfillmentNetworkDetails that = ((FulfillmentNetworkDetails) object);
        {
            String lhsFulfillmentNetworkCustomerCode;
            lhsFulfillmentNetworkCustomerCode = this.getFulfillmentNetworkCustomerCode();
            String rhsFulfillmentNetworkCustomerCode;
            rhsFulfillmentNetworkCustomerCode = that.getFulfillmentNetworkCustomerCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fulfillmentNetworkCustomerCode", lhsFulfillmentNetworkCustomerCode), LocatorUtils.property(thatLocator, "fulfillmentNetworkCustomerCode", rhsFulfillmentNetworkCustomerCode), lhsFulfillmentNetworkCustomerCode, rhsFulfillmentNetworkCustomerCode, (this.fulfillmentNetworkCustomerCode!= null), (that.fulfillmentNetworkCustomerCode!= null))) {
                return false;
            }
        }
        {
            String lhsFulfillmentNetworkUrl;
            lhsFulfillmentNetworkUrl = this.getFulfillmentNetworkUrl();
            String rhsFulfillmentNetworkUrl;
            rhsFulfillmentNetworkUrl = that.getFulfillmentNetworkUrl();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fulfillmentNetworkUrl", lhsFulfillmentNetworkUrl), LocatorUtils.property(thatLocator, "fulfillmentNetworkUrl", rhsFulfillmentNetworkUrl), lhsFulfillmentNetworkUrl, rhsFulfillmentNetworkUrl, (this.fulfillmentNetworkUrl!= null), (that.fulfillmentNetworkUrl!= null))) {
                return false;
            }
        }
        {
            RequestExpiryType lhsRequestExpiryType;
            lhsRequestExpiryType = this.getRequestExpiryType();
            RequestExpiryType rhsRequestExpiryType;
            rhsRequestExpiryType = that.getRequestExpiryType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "requestExpiryType", lhsRequestExpiryType), LocatorUtils.property(thatLocator, "requestExpiryType", rhsRequestExpiryType), lhsRequestExpiryType, rhsRequestExpiryType, (this.requestExpiryType!= null), (that.requestExpiryType!= null))) {
                return false;
            }
        }
        {
            Integer lhsExpiryTime;
            lhsExpiryTime = this.getExpiryTime();
            Integer rhsExpiryTime;
            rhsExpiryTime = that.getExpiryTime();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "expiryTime", lhsExpiryTime), LocatorUtils.property(thatLocator, "expiryTime", rhsExpiryTime), lhsExpiryTime, rhsExpiryTime, (this.expiryTime!= null), (that.expiryTime!= null))) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            String theFulfillmentNetworkCustomerCode;
            theFulfillmentNetworkCustomerCode = this.getFulfillmentNetworkCustomerCode();
            strategy.appendField(locator, this, "fulfillmentNetworkCustomerCode", buffer, theFulfillmentNetworkCustomerCode, (this.fulfillmentNetworkCustomerCode!= null));
        }
        {
            String theFulfillmentNetworkUrl;
            theFulfillmentNetworkUrl = this.getFulfillmentNetworkUrl();
            strategy.appendField(locator, this, "fulfillmentNetworkUrl", buffer, theFulfillmentNetworkUrl, (this.fulfillmentNetworkUrl!= null));
        }
        {
            RequestExpiryType theRequestExpiryType;
            theRequestExpiryType = this.getRequestExpiryType();
            strategy.appendField(locator, this, "requestExpiryType", buffer, theRequestExpiryType, (this.requestExpiryType!= null));
        }
        {
            Integer theExpiryTime;
            theExpiryTime = this.getExpiryTime();
            strategy.appendField(locator, this, "expiryTime", buffer, theExpiryTime, (this.expiryTime!= null));
        }
        return buffer;
    }

}
