//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.12 at 09:27:55 AM CET 
//


package no.bibsys.alma.rest.holdings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.bibsys.alma.rest.holdings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Holdings_QNAME = new QName("", "holdings");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.bibsys.alma.rest.holdings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Holding }
     * 
     */
    public Holding createHolding() {
        return new Holding();
    }

    /**
     * Create an instance of {@link Holdings }
     * 
     */
    public Holdings createHoldings() {
        return new Holdings();
    }

    /**
     * Create an instance of {@link BibData }
     * 
     */
    public BibData createBibData() {
        return new BibData();
    }

    /**
     * Create an instance of {@link NetworkNumbers }
     * 
     */
    public NetworkNumbers createNetworkNumbers() {
        return new NetworkNumbers();
    }

    /**
     * Create an instance of {@link Holding.Library }
     * 
     */
    public Holding.Library createHoldingLibrary() {
        return new Holding.Library();
    }

    /**
     * Create an instance of {@link Holding.Location }
     * 
     */
    public Holding.Location createHoldingLocation() {
        return new Holding.Location();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Holdings }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "holdings")
    public JAXBElement<Holdings> createHoldings(Holdings value) {
        return new JAXBElement<Holdings>(_Holdings_QNAME, Holdings.class, null, value);
    }

}
