//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.12 at 09:54:26 AM CET 
//


package no.bibsys.alma.rest.ncip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.niso.org/2008/ncip}InitiationHeader" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.niso.org/2008/ncip}ItemId"/&gt;
 *         &lt;element ref="{http://www.niso.org/2008/ncip}UserId"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://www.niso.org/2008/ncip}ItemReportedReturned"/&gt;
 *           &lt;element ref="{http://www.niso.org/2008/ncip}ItemReportedNeverBorrowed"/&gt;
 *           &lt;element ref="{http://www.niso.org/2008/ncip}ItemReportedLost"/&gt;
 *           &lt;element ref="{http://www.niso.org/2008/ncip}ItemReportedMissing"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://www.niso.org/2008/ncip}ItemOptionalFields" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.niso.org/2008/ncip}UserOptionalFields" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.niso.org/2008/ncip}FiscalTransactionInformation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Ext" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "initiationHeader",
    "itemId",
    "userId",
    "itemReportedMissing",
    "itemReportedLost",
    "itemReportedNeverBorrowed",
    "itemReportedReturned",
    "itemOptionalFields",
    "userOptionalFields",
    "fiscalTransactionInformation",
    "ext"
})
@XmlRootElement(name = "CirculationStatusChangeReported")
public class CirculationStatusChangeReported implements Equals2, HashCode2, ToString2
{

    @XmlElement(name = "InitiationHeader")
    protected InitiationHeader initiationHeader;
    @XmlElement(name = "ItemId", required = true)
    protected ItemId itemId;
    @XmlElement(name = "UserId", required = true)
    protected UserId userId;
    @XmlElement(name = "ItemReportedMissing")
    protected ItemReportedMissing itemReportedMissing;
    @XmlElement(name = "ItemReportedLost")
    protected ItemReportedLost itemReportedLost;
    @XmlElement(name = "ItemReportedNeverBorrowed")
    protected ItemReportedNeverBorrowed itemReportedNeverBorrowed;
    @XmlElement(name = "ItemReportedReturned")
    protected ItemReportedReturned itemReportedReturned;
    @XmlElement(name = "ItemOptionalFields")
    protected ItemOptionalFields itemOptionalFields;
    @XmlElement(name = "UserOptionalFields")
    protected UserOptionalFields userOptionalFields;
    @XmlElement(name = "FiscalTransactionInformation")
    protected FiscalTransactionInformation fiscalTransactionInformation;
    @XmlElement(name = "Ext")
    protected Ext ext;

    /**
     * Gets the value of the initiationHeader property.
     * 
     * @return
     *     possible object is
     *     {@link InitiationHeader }
     *     
     */
    public InitiationHeader getInitiationHeader() {
        return initiationHeader;
    }

    /**
     * Sets the value of the initiationHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitiationHeader }
     *     
     */
    public void setInitiationHeader(InitiationHeader value) {
        this.initiationHeader = value;
    }

    /**
     * Gets the value of the itemId property.
     * 
     * @return
     *     possible object is
     *     {@link ItemId }
     *     
     */
    public ItemId getItemId() {
        return itemId;
    }

    /**
     * Sets the value of the itemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemId }
     *     
     */
    public void setItemId(ItemId value) {
        this.itemId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link UserId }
     *     
     */
    public UserId getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserId }
     *     
     */
    public void setUserId(UserId value) {
        this.userId = value;
    }

    /**
     * Gets the value of the itemReportedMissing property.
     * 
     * @return
     *     possible object is
     *     {@link ItemReportedMissing }
     *     
     */
    public ItemReportedMissing getItemReportedMissing() {
        return itemReportedMissing;
    }

    /**
     * Sets the value of the itemReportedMissing property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemReportedMissing }
     *     
     */
    public void setItemReportedMissing(ItemReportedMissing value) {
        this.itemReportedMissing = value;
    }

    /**
     * Gets the value of the itemReportedLost property.
     * 
     * @return
     *     possible object is
     *     {@link ItemReportedLost }
     *     
     */
    public ItemReportedLost getItemReportedLost() {
        return itemReportedLost;
    }

    /**
     * Sets the value of the itemReportedLost property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemReportedLost }
     *     
     */
    public void setItemReportedLost(ItemReportedLost value) {
        this.itemReportedLost = value;
    }

    /**
     * Gets the value of the itemReportedNeverBorrowed property.
     * 
     * @return
     *     possible object is
     *     {@link ItemReportedNeverBorrowed }
     *     
     */
    public ItemReportedNeverBorrowed getItemReportedNeverBorrowed() {
        return itemReportedNeverBorrowed;
    }

    /**
     * Sets the value of the itemReportedNeverBorrowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemReportedNeverBorrowed }
     *     
     */
    public void setItemReportedNeverBorrowed(ItemReportedNeverBorrowed value) {
        this.itemReportedNeverBorrowed = value;
    }

    /**
     * Gets the value of the itemReportedReturned property.
     * 
     * @return
     *     possible object is
     *     {@link ItemReportedReturned }
     *     
     */
    public ItemReportedReturned getItemReportedReturned() {
        return itemReportedReturned;
    }

    /**
     * Sets the value of the itemReportedReturned property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemReportedReturned }
     *     
     */
    public void setItemReportedReturned(ItemReportedReturned value) {
        this.itemReportedReturned = value;
    }

    /**
     * Gets the value of the itemOptionalFields property.
     * 
     * @return
     *     possible object is
     *     {@link ItemOptionalFields }
     *     
     */
    public ItemOptionalFields getItemOptionalFields() {
        return itemOptionalFields;
    }

    /**
     * Sets the value of the itemOptionalFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemOptionalFields }
     *     
     */
    public void setItemOptionalFields(ItemOptionalFields value) {
        this.itemOptionalFields = value;
    }

    /**
     * Gets the value of the userOptionalFields property.
     * 
     * @return
     *     possible object is
     *     {@link UserOptionalFields }
     *     
     */
    public UserOptionalFields getUserOptionalFields() {
        return userOptionalFields;
    }

    /**
     * Sets the value of the userOptionalFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserOptionalFields }
     *     
     */
    public void setUserOptionalFields(UserOptionalFields value) {
        this.userOptionalFields = value;
    }

    /**
     * Gets the value of the fiscalTransactionInformation property.
     * 
     * @return
     *     possible object is
     *     {@link FiscalTransactionInformation }
     *     
     */
    public FiscalTransactionInformation getFiscalTransactionInformation() {
        return fiscalTransactionInformation;
    }

    /**
     * Sets the value of the fiscalTransactionInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiscalTransactionInformation }
     *     
     */
    public void setFiscalTransactionInformation(FiscalTransactionInformation value) {
        this.fiscalTransactionInformation = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link Ext }
     *     
     */
    public Ext getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ext }
     *     
     */
    public void setExt(Ext value) {
        this.ext = value;
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            InitiationHeader theInitiationHeader;
            theInitiationHeader = this.getInitiationHeader();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "initiationHeader", theInitiationHeader), currentHashCode, theInitiationHeader, (this.initiationHeader!= null));
        }
        {
            ItemId theItemId;
            theItemId = this.getItemId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "itemId", theItemId), currentHashCode, theItemId, (this.itemId!= null));
        }
        {
            UserId theUserId;
            theUserId = this.getUserId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "userId", theUserId), currentHashCode, theUserId, (this.userId!= null));
        }
        {
            ItemReportedMissing theItemReportedMissing;
            theItemReportedMissing = this.getItemReportedMissing();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "itemReportedMissing", theItemReportedMissing), currentHashCode, theItemReportedMissing, (this.itemReportedMissing!= null));
        }
        {
            ItemReportedLost theItemReportedLost;
            theItemReportedLost = this.getItemReportedLost();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "itemReportedLost", theItemReportedLost), currentHashCode, theItemReportedLost, (this.itemReportedLost!= null));
        }
        {
            ItemReportedNeverBorrowed theItemReportedNeverBorrowed;
            theItemReportedNeverBorrowed = this.getItemReportedNeverBorrowed();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "itemReportedNeverBorrowed", theItemReportedNeverBorrowed), currentHashCode, theItemReportedNeverBorrowed, (this.itemReportedNeverBorrowed!= null));
        }
        {
            ItemReportedReturned theItemReportedReturned;
            theItemReportedReturned = this.getItemReportedReturned();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "itemReportedReturned", theItemReportedReturned), currentHashCode, theItemReportedReturned, (this.itemReportedReturned!= null));
        }
        {
            ItemOptionalFields theItemOptionalFields;
            theItemOptionalFields = this.getItemOptionalFields();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "itemOptionalFields", theItemOptionalFields), currentHashCode, theItemOptionalFields, (this.itemOptionalFields!= null));
        }
        {
            UserOptionalFields theUserOptionalFields;
            theUserOptionalFields = this.getUserOptionalFields();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "userOptionalFields", theUserOptionalFields), currentHashCode, theUserOptionalFields, (this.userOptionalFields!= null));
        }
        {
            FiscalTransactionInformation theFiscalTransactionInformation;
            theFiscalTransactionInformation = this.getFiscalTransactionInformation();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fiscalTransactionInformation", theFiscalTransactionInformation), currentHashCode, theFiscalTransactionInformation, (this.fiscalTransactionInformation!= null));
        }
        {
            Ext theExt;
            theExt = this.getExt();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ext", theExt), currentHashCode, theExt, (this.ext!= null));
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final CirculationStatusChangeReported that = ((CirculationStatusChangeReported) object);
        {
            InitiationHeader lhsInitiationHeader;
            lhsInitiationHeader = this.getInitiationHeader();
            InitiationHeader rhsInitiationHeader;
            rhsInitiationHeader = that.getInitiationHeader();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "initiationHeader", lhsInitiationHeader), LocatorUtils.property(thatLocator, "initiationHeader", rhsInitiationHeader), lhsInitiationHeader, rhsInitiationHeader, (this.initiationHeader!= null), (that.initiationHeader!= null))) {
                return false;
            }
        }
        {
            ItemId lhsItemId;
            lhsItemId = this.getItemId();
            ItemId rhsItemId;
            rhsItemId = that.getItemId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "itemId", lhsItemId), LocatorUtils.property(thatLocator, "itemId", rhsItemId), lhsItemId, rhsItemId, (this.itemId!= null), (that.itemId!= null))) {
                return false;
            }
        }
        {
            UserId lhsUserId;
            lhsUserId = this.getUserId();
            UserId rhsUserId;
            rhsUserId = that.getUserId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "userId", lhsUserId), LocatorUtils.property(thatLocator, "userId", rhsUserId), lhsUserId, rhsUserId, (this.userId!= null), (that.userId!= null))) {
                return false;
            }
        }
        {
            ItemReportedMissing lhsItemReportedMissing;
            lhsItemReportedMissing = this.getItemReportedMissing();
            ItemReportedMissing rhsItemReportedMissing;
            rhsItemReportedMissing = that.getItemReportedMissing();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "itemReportedMissing", lhsItemReportedMissing), LocatorUtils.property(thatLocator, "itemReportedMissing", rhsItemReportedMissing), lhsItemReportedMissing, rhsItemReportedMissing, (this.itemReportedMissing!= null), (that.itemReportedMissing!= null))) {
                return false;
            }
        }
        {
            ItemReportedLost lhsItemReportedLost;
            lhsItemReportedLost = this.getItemReportedLost();
            ItemReportedLost rhsItemReportedLost;
            rhsItemReportedLost = that.getItemReportedLost();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "itemReportedLost", lhsItemReportedLost), LocatorUtils.property(thatLocator, "itemReportedLost", rhsItemReportedLost), lhsItemReportedLost, rhsItemReportedLost, (this.itemReportedLost!= null), (that.itemReportedLost!= null))) {
                return false;
            }
        }
        {
            ItemReportedNeverBorrowed lhsItemReportedNeverBorrowed;
            lhsItemReportedNeverBorrowed = this.getItemReportedNeverBorrowed();
            ItemReportedNeverBorrowed rhsItemReportedNeverBorrowed;
            rhsItemReportedNeverBorrowed = that.getItemReportedNeverBorrowed();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "itemReportedNeverBorrowed", lhsItemReportedNeverBorrowed), LocatorUtils.property(thatLocator, "itemReportedNeverBorrowed", rhsItemReportedNeverBorrowed), lhsItemReportedNeverBorrowed, rhsItemReportedNeverBorrowed, (this.itemReportedNeverBorrowed!= null), (that.itemReportedNeverBorrowed!= null))) {
                return false;
            }
        }
        {
            ItemReportedReturned lhsItemReportedReturned;
            lhsItemReportedReturned = this.getItemReportedReturned();
            ItemReportedReturned rhsItemReportedReturned;
            rhsItemReportedReturned = that.getItemReportedReturned();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "itemReportedReturned", lhsItemReportedReturned), LocatorUtils.property(thatLocator, "itemReportedReturned", rhsItemReportedReturned), lhsItemReportedReturned, rhsItemReportedReturned, (this.itemReportedReturned!= null), (that.itemReportedReturned!= null))) {
                return false;
            }
        }
        {
            ItemOptionalFields lhsItemOptionalFields;
            lhsItemOptionalFields = this.getItemOptionalFields();
            ItemOptionalFields rhsItemOptionalFields;
            rhsItemOptionalFields = that.getItemOptionalFields();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "itemOptionalFields", lhsItemOptionalFields), LocatorUtils.property(thatLocator, "itemOptionalFields", rhsItemOptionalFields), lhsItemOptionalFields, rhsItemOptionalFields, (this.itemOptionalFields!= null), (that.itemOptionalFields!= null))) {
                return false;
            }
        }
        {
            UserOptionalFields lhsUserOptionalFields;
            lhsUserOptionalFields = this.getUserOptionalFields();
            UserOptionalFields rhsUserOptionalFields;
            rhsUserOptionalFields = that.getUserOptionalFields();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "userOptionalFields", lhsUserOptionalFields), LocatorUtils.property(thatLocator, "userOptionalFields", rhsUserOptionalFields), lhsUserOptionalFields, rhsUserOptionalFields, (this.userOptionalFields!= null), (that.userOptionalFields!= null))) {
                return false;
            }
        }
        {
            FiscalTransactionInformation lhsFiscalTransactionInformation;
            lhsFiscalTransactionInformation = this.getFiscalTransactionInformation();
            FiscalTransactionInformation rhsFiscalTransactionInformation;
            rhsFiscalTransactionInformation = that.getFiscalTransactionInformation();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fiscalTransactionInformation", lhsFiscalTransactionInformation), LocatorUtils.property(thatLocator, "fiscalTransactionInformation", rhsFiscalTransactionInformation), lhsFiscalTransactionInformation, rhsFiscalTransactionInformation, (this.fiscalTransactionInformation!= null), (that.fiscalTransactionInformation!= null))) {
                return false;
            }
        }
        {
            Ext lhsExt;
            lhsExt = this.getExt();
            Ext rhsExt;
            rhsExt = that.getExt();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ext", lhsExt), LocatorUtils.property(thatLocator, "ext", rhsExt), lhsExt, rhsExt, (this.ext!= null), (that.ext!= null))) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            InitiationHeader theInitiationHeader;
            theInitiationHeader = this.getInitiationHeader();
            strategy.appendField(locator, this, "initiationHeader", buffer, theInitiationHeader, (this.initiationHeader!= null));
        }
        {
            ItemId theItemId;
            theItemId = this.getItemId();
            strategy.appendField(locator, this, "itemId", buffer, theItemId, (this.itemId!= null));
        }
        {
            UserId theUserId;
            theUserId = this.getUserId();
            strategy.appendField(locator, this, "userId", buffer, theUserId, (this.userId!= null));
        }
        {
            ItemReportedMissing theItemReportedMissing;
            theItemReportedMissing = this.getItemReportedMissing();
            strategy.appendField(locator, this, "itemReportedMissing", buffer, theItemReportedMissing, (this.itemReportedMissing!= null));
        }
        {
            ItemReportedLost theItemReportedLost;
            theItemReportedLost = this.getItemReportedLost();
            strategy.appendField(locator, this, "itemReportedLost", buffer, theItemReportedLost, (this.itemReportedLost!= null));
        }
        {
            ItemReportedNeverBorrowed theItemReportedNeverBorrowed;
            theItemReportedNeverBorrowed = this.getItemReportedNeverBorrowed();
            strategy.appendField(locator, this, "itemReportedNeverBorrowed", buffer, theItemReportedNeverBorrowed, (this.itemReportedNeverBorrowed!= null));
        }
        {
            ItemReportedReturned theItemReportedReturned;
            theItemReportedReturned = this.getItemReportedReturned();
            strategy.appendField(locator, this, "itemReportedReturned", buffer, theItemReportedReturned, (this.itemReportedReturned!= null));
        }
        {
            ItemOptionalFields theItemOptionalFields;
            theItemOptionalFields = this.getItemOptionalFields();
            strategy.appendField(locator, this, "itemOptionalFields", buffer, theItemOptionalFields, (this.itemOptionalFields!= null));
        }
        {
            UserOptionalFields theUserOptionalFields;
            theUserOptionalFields = this.getUserOptionalFields();
            strategy.appendField(locator, this, "userOptionalFields", buffer, theUserOptionalFields, (this.userOptionalFields!= null));
        }
        {
            FiscalTransactionInformation theFiscalTransactionInformation;
            theFiscalTransactionInformation = this.getFiscalTransactionInformation();
            strategy.appendField(locator, this, "fiscalTransactionInformation", buffer, theFiscalTransactionInformation, (this.fiscalTransactionInformation!= null));
        }
        {
            Ext theExt;
            theExt = this.getExt();
            strategy.appendField(locator, this, "ext", buffer, theExt, (this.ext!= null));
        }
        return buffer;
    }

}
