//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.12 at 09:54:26 AM CET 
//


package no.bibsys.alma.rest.ncip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.niso.org/2008/ncip}UserPrivilegeStatusType"/&gt;
 *         &lt;element ref="{http://www.niso.org/2008/ncip}DateOfUserPrivilegeStatus" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Ext" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userPrivilegeStatusType",
    "dateOfUserPrivilegeStatus",
    "ext"
})
@XmlRootElement(name = "UserPrivilegeStatus")
public class UserPrivilegeStatus implements Equals2, HashCode2, ToString2
{

    @XmlElement(name = "UserPrivilegeStatusType", required = true)
    protected SchemeValuePair userPrivilegeStatusType;
    @XmlElement(name = "DateOfUserPrivilegeStatus")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateOfUserPrivilegeStatus;
    @XmlElement(name = "Ext")
    protected Ext ext;

    /**
     * Gets the value of the userPrivilegeStatusType property.
     * 
     * @return
     *     possible object is
     *     {@link SchemeValuePair }
     *     
     */
    public SchemeValuePair getUserPrivilegeStatusType() {
        return userPrivilegeStatusType;
    }

    /**
     * Sets the value of the userPrivilegeStatusType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemeValuePair }
     *     
     */
    public void setUserPrivilegeStatusType(SchemeValuePair value) {
        this.userPrivilegeStatusType = value;
    }

    /**
     * Gets the value of the dateOfUserPrivilegeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfUserPrivilegeStatus() {
        return dateOfUserPrivilegeStatus;
    }

    /**
     * Sets the value of the dateOfUserPrivilegeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfUserPrivilegeStatus(XMLGregorianCalendar value) {
        this.dateOfUserPrivilegeStatus = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link Ext }
     *     
     */
    public Ext getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ext }
     *     
     */
    public void setExt(Ext value) {
        this.ext = value;
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            SchemeValuePair theUserPrivilegeStatusType;
            theUserPrivilegeStatusType = this.getUserPrivilegeStatusType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "userPrivilegeStatusType", theUserPrivilegeStatusType), currentHashCode, theUserPrivilegeStatusType, (this.userPrivilegeStatusType!= null));
        }
        {
            XMLGregorianCalendar theDateOfUserPrivilegeStatus;
            theDateOfUserPrivilegeStatus = this.getDateOfUserPrivilegeStatus();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "dateOfUserPrivilegeStatus", theDateOfUserPrivilegeStatus), currentHashCode, theDateOfUserPrivilegeStatus, (this.dateOfUserPrivilegeStatus!= null));
        }
        {
            Ext theExt;
            theExt = this.getExt();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ext", theExt), currentHashCode, theExt, (this.ext!= null));
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final UserPrivilegeStatus that = ((UserPrivilegeStatus) object);
        {
            SchemeValuePair lhsUserPrivilegeStatusType;
            lhsUserPrivilegeStatusType = this.getUserPrivilegeStatusType();
            SchemeValuePair rhsUserPrivilegeStatusType;
            rhsUserPrivilegeStatusType = that.getUserPrivilegeStatusType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "userPrivilegeStatusType", lhsUserPrivilegeStatusType), LocatorUtils.property(thatLocator, "userPrivilegeStatusType", rhsUserPrivilegeStatusType), lhsUserPrivilegeStatusType, rhsUserPrivilegeStatusType, (this.userPrivilegeStatusType!= null), (that.userPrivilegeStatusType!= null))) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsDateOfUserPrivilegeStatus;
            lhsDateOfUserPrivilegeStatus = this.getDateOfUserPrivilegeStatus();
            XMLGregorianCalendar rhsDateOfUserPrivilegeStatus;
            rhsDateOfUserPrivilegeStatus = that.getDateOfUserPrivilegeStatus();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "dateOfUserPrivilegeStatus", lhsDateOfUserPrivilegeStatus), LocatorUtils.property(thatLocator, "dateOfUserPrivilegeStatus", rhsDateOfUserPrivilegeStatus), lhsDateOfUserPrivilegeStatus, rhsDateOfUserPrivilegeStatus, (this.dateOfUserPrivilegeStatus!= null), (that.dateOfUserPrivilegeStatus!= null))) {
                return false;
            }
        }
        {
            Ext lhsExt;
            lhsExt = this.getExt();
            Ext rhsExt;
            rhsExt = that.getExt();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ext", lhsExt), LocatorUtils.property(thatLocator, "ext", rhsExt), lhsExt, rhsExt, (this.ext!= null), (that.ext!= null))) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            SchemeValuePair theUserPrivilegeStatusType;
            theUserPrivilegeStatusType = this.getUserPrivilegeStatusType();
            strategy.appendField(locator, this, "userPrivilegeStatusType", buffer, theUserPrivilegeStatusType, (this.userPrivilegeStatusType!= null));
        }
        {
            XMLGregorianCalendar theDateOfUserPrivilegeStatus;
            theDateOfUserPrivilegeStatus = this.getDateOfUserPrivilegeStatus();
            strategy.appendField(locator, this, "dateOfUserPrivilegeStatus", buffer, theDateOfUserPrivilegeStatus, (this.dateOfUserPrivilegeStatus!= null));
        }
        {
            Ext theExt;
            theExt = this.getExt();
            strategy.appendField(locator, this, "ext", buffer, theExt, (this.ext!= null));
        }
        return buffer;
    }

}
