//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.12 at 09:54:26 AM CET 
//


package no.bibsys.alma.rest.ncip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.niso.org/2008/ncip}UserAddressRoleType"/&gt;
 *         &lt;element ref="{http://www.niso.org/2008/ncip}ValidFromDate" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.niso.org/2008/ncip}ValidToDate" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://www.niso.org/2008/ncip}PhysicalAddress"/&gt;
 *           &lt;element ref="{http://www.niso.org/2008/ncip}ElectronicAddress"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Ext" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userAddressRoleType",
    "validFromDate",
    "validToDate",
    "electronicAddress",
    "physicalAddress",
    "ext"
})
@XmlRootElement(name = "UserAddressInformation")
public class UserAddressInformation implements Equals2, HashCode2, ToString2
{

    @XmlElement(name = "UserAddressRoleType", required = true)
    protected SchemeValuePair userAddressRoleType;
    @XmlElement(name = "ValidFromDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validFromDate;
    @XmlElement(name = "ValidToDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validToDate;
    @XmlElement(name = "ElectronicAddress")
    protected ElectronicAddress electronicAddress;
    @XmlElement(name = "PhysicalAddress")
    protected PhysicalAddress physicalAddress;
    @XmlElement(name = "Ext")
    protected Ext ext;

    /**
     * Gets the value of the userAddressRoleType property.
     * 
     * @return
     *     possible object is
     *     {@link SchemeValuePair }
     *     
     */
    public SchemeValuePair getUserAddressRoleType() {
        return userAddressRoleType;
    }

    /**
     * Sets the value of the userAddressRoleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemeValuePair }
     *     
     */
    public void setUserAddressRoleType(SchemeValuePair value) {
        this.userAddressRoleType = value;
    }

    /**
     * Gets the value of the validFromDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidFromDate() {
        return validFromDate;
    }

    /**
     * Sets the value of the validFromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidFromDate(XMLGregorianCalendar value) {
        this.validFromDate = value;
    }

    /**
     * Gets the value of the validToDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidToDate() {
        return validToDate;
    }

    /**
     * Sets the value of the validToDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidToDate(XMLGregorianCalendar value) {
        this.validToDate = value;
    }

    /**
     * Gets the value of the electronicAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ElectronicAddress }
     *     
     */
    public ElectronicAddress getElectronicAddress() {
        return electronicAddress;
    }

    /**
     * Sets the value of the electronicAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectronicAddress }
     *     
     */
    public void setElectronicAddress(ElectronicAddress value) {
        this.electronicAddress = value;
    }

    /**
     * Gets the value of the physicalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalAddress }
     *     
     */
    public PhysicalAddress getPhysicalAddress() {
        return physicalAddress;
    }

    /**
     * Sets the value of the physicalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalAddress }
     *     
     */
    public void setPhysicalAddress(PhysicalAddress value) {
        this.physicalAddress = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link Ext }
     *     
     */
    public Ext getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ext }
     *     
     */
    public void setExt(Ext value) {
        this.ext = value;
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            SchemeValuePair theUserAddressRoleType;
            theUserAddressRoleType = this.getUserAddressRoleType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "userAddressRoleType", theUserAddressRoleType), currentHashCode, theUserAddressRoleType, (this.userAddressRoleType!= null));
        }
        {
            XMLGregorianCalendar theValidFromDate;
            theValidFromDate = this.getValidFromDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "validFromDate", theValidFromDate), currentHashCode, theValidFromDate, (this.validFromDate!= null));
        }
        {
            XMLGregorianCalendar theValidToDate;
            theValidToDate = this.getValidToDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "validToDate", theValidToDate), currentHashCode, theValidToDate, (this.validToDate!= null));
        }
        {
            ElectronicAddress theElectronicAddress;
            theElectronicAddress = this.getElectronicAddress();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "electronicAddress", theElectronicAddress), currentHashCode, theElectronicAddress, (this.electronicAddress!= null));
        }
        {
            PhysicalAddress thePhysicalAddress;
            thePhysicalAddress = this.getPhysicalAddress();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "physicalAddress", thePhysicalAddress), currentHashCode, thePhysicalAddress, (this.physicalAddress!= null));
        }
        {
            Ext theExt;
            theExt = this.getExt();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ext", theExt), currentHashCode, theExt, (this.ext!= null));
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final UserAddressInformation that = ((UserAddressInformation) object);
        {
            SchemeValuePair lhsUserAddressRoleType;
            lhsUserAddressRoleType = this.getUserAddressRoleType();
            SchemeValuePair rhsUserAddressRoleType;
            rhsUserAddressRoleType = that.getUserAddressRoleType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "userAddressRoleType", lhsUserAddressRoleType), LocatorUtils.property(thatLocator, "userAddressRoleType", rhsUserAddressRoleType), lhsUserAddressRoleType, rhsUserAddressRoleType, (this.userAddressRoleType!= null), (that.userAddressRoleType!= null))) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsValidFromDate;
            lhsValidFromDate = this.getValidFromDate();
            XMLGregorianCalendar rhsValidFromDate;
            rhsValidFromDate = that.getValidFromDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "validFromDate", lhsValidFromDate), LocatorUtils.property(thatLocator, "validFromDate", rhsValidFromDate), lhsValidFromDate, rhsValidFromDate, (this.validFromDate!= null), (that.validFromDate!= null))) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsValidToDate;
            lhsValidToDate = this.getValidToDate();
            XMLGregorianCalendar rhsValidToDate;
            rhsValidToDate = that.getValidToDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "validToDate", lhsValidToDate), LocatorUtils.property(thatLocator, "validToDate", rhsValidToDate), lhsValidToDate, rhsValidToDate, (this.validToDate!= null), (that.validToDate!= null))) {
                return false;
            }
        }
        {
            ElectronicAddress lhsElectronicAddress;
            lhsElectronicAddress = this.getElectronicAddress();
            ElectronicAddress rhsElectronicAddress;
            rhsElectronicAddress = that.getElectronicAddress();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "electronicAddress", lhsElectronicAddress), LocatorUtils.property(thatLocator, "electronicAddress", rhsElectronicAddress), lhsElectronicAddress, rhsElectronicAddress, (this.electronicAddress!= null), (that.electronicAddress!= null))) {
                return false;
            }
        }
        {
            PhysicalAddress lhsPhysicalAddress;
            lhsPhysicalAddress = this.getPhysicalAddress();
            PhysicalAddress rhsPhysicalAddress;
            rhsPhysicalAddress = that.getPhysicalAddress();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "physicalAddress", lhsPhysicalAddress), LocatorUtils.property(thatLocator, "physicalAddress", rhsPhysicalAddress), lhsPhysicalAddress, rhsPhysicalAddress, (this.physicalAddress!= null), (that.physicalAddress!= null))) {
                return false;
            }
        }
        {
            Ext lhsExt;
            lhsExt = this.getExt();
            Ext rhsExt;
            rhsExt = that.getExt();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ext", lhsExt), LocatorUtils.property(thatLocator, "ext", rhsExt), lhsExt, rhsExt, (this.ext!= null), (that.ext!= null))) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            SchemeValuePair theUserAddressRoleType;
            theUserAddressRoleType = this.getUserAddressRoleType();
            strategy.appendField(locator, this, "userAddressRoleType", buffer, theUserAddressRoleType, (this.userAddressRoleType!= null));
        }
        {
            XMLGregorianCalendar theValidFromDate;
            theValidFromDate = this.getValidFromDate();
            strategy.appendField(locator, this, "validFromDate", buffer, theValidFromDate, (this.validFromDate!= null));
        }
        {
            XMLGregorianCalendar theValidToDate;
            theValidToDate = this.getValidToDate();
            strategy.appendField(locator, this, "validToDate", buffer, theValidToDate, (this.validToDate!= null));
        }
        {
            ElectronicAddress theElectronicAddress;
            theElectronicAddress = this.getElectronicAddress();
            strategy.appendField(locator, this, "electronicAddress", buffer, theElectronicAddress, (this.electronicAddress!= null));
        }
        {
            PhysicalAddress thePhysicalAddress;
            thePhysicalAddress = this.getPhysicalAddress();
            strategy.appendField(locator, this, "physicalAddress", buffer, thePhysicalAddress, (this.physicalAddress!= null));
        }
        {
            Ext theExt;
            theExt = this.getExt();
            strategy.appendField(locator, this, "ext", buffer, theExt, (this.ext!= null));
        }
        return buffer;
    }

}
